### ISSUE TITLE
adRoot has potential to flicker elements

### ISSUE THREAD

**Issue by hookmark** [chrisathook/display-html5-compass#2]
The solution may simply be to better understand the difference between this and the standard template. However, there was a case on a Search 970 where elements were all up for a split second at the start of the banner since adRoot's opacity was not set to 0 in the sass. This may have been user error in removing the opacity 0 from the collapsed content container. If this is not a technical issue, it's an education issue.

**Comment by chrisathook** [comment]
the content div inside each partial is set to opacity 0 in the style.scss. and is made visible later. As long as all the content is inside those divs within each partial nothing should be visible until told to be so by the developer.
